import "../globals.css";

export const metadata = {
  title: "Studio",
  description: "Generated by Next + Sanity",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Studio</title>
      </head>
      <body>{children}</body>
    </html>
  );
}
